name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USERNAME }}/${{ secrets.USERNAME }}
          token: ${{ secrets.SECRET }}
      
      - name: Fetch joke
        run: |
          JOKE_DATA=$(curl -s ${{ secrets.JOKE_URL }})
          SETUP=$(echo $JOKE_DATA | jq -r '.setup')
          PUNCHLINE=$(echo $JOKE_DATA | jq -r '.punchline')
          echo "<div align=\"center\">" > joke.txt
          echo "  <i>⚡ \"$SETUP - $PUNCHLINE\"</i>" >> joke.txt
          echo "</div>" >> joke.txt

      - name: Fetch latest blog posts
        run: |
          BLOG_DATA=$(curl -s https://atakangul.com/blogs/most-viewed)
          echo "Raw API response:"
          echo "$BLOG_DATA"
          if jq -e . >/dev/null 2>&1 <<<"$BLOG_DATA"; then
            echo $BLOG_DATA | jq -r 'if type == "array" then .[0:3] else . end | if type == "array" then map("- [\(.title // \"No Title\")](https://atakangul.com/blogs/\(.url // \"\"))") | join("\n") else "Error: Unexpected data structure" end' > blog_posts.txt
          else
            echo "Error: Invalid JSON response from API" > blog_posts.txt
          fi
          echo "Processed blog posts:"
          cat blog_posts.txt

      - name: Update README
        run: |
          awk '
          BEGIN {
            blog_start = 0
            quote = 0
          }
          /<!-- BLOG-POST-LIST:START -->/ {
            print
            system("cat blog_posts.txt")
            blog_start = 1
            next
          }
          /<div align="center">.*"Infrastructure as code:/ {
            system("cat joke.txt")
            quote = 1
            next
          }
          blog_start && /<!-- BLOG-POST-LIST:END -->/ {
            print
            blog_start = 0
            next
          }
          !blog_start && !quote {
            print
          }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.USERNAME }}"
          git add README.md
          git commit -m "Update README with latest joke and blog posts" || exit 0
          git push https://${{ secrets.SECRET }}@github.com/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}.git
