name: Daily Joke Update
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USERNAME }}/${{ secrets.USERNAME }}
          token: ${{ secrets.SECRET }}
      - name: Fetch joke and update README
        run: |
          JOKE_DATA=$(curl -s ${{ secrets.JOKE_URL }})
          SETUP=$(echo $JOKE_DATA | jq -r '.setup')
          PUNCHLINE=$(echo $JOKE_DATA | jq -r '.punchline')
          
          JOKE="## **10 min/joke:**\n\n$SETUP\n\n$PUNCHLINE"
         
          sed -i '/<!-- JOKE-START -->/,/<!-- JOKE-END -->/c\<!-- JOKE-START -->\n'"- $JOKE"'\n<!-- JOKE-END -->' README.md
          
          if ! grep -q "<!-- JOKE-START -->" README.md; then
            echo -e "\n<!-- JOKE-START -->\n- $JOKE\n<!-- JOKE-END -->" >> README.md
          fi
      - name: Commit and push changes
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
          git add README.md
          git commit -m "Update daily joke" || exit 0
          git push https://${{ secrets.SECRET }}@github.com/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}.git
