name: Daily README Update
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USERNAME }}/${{ secrets.USERNAME }}
          token: ${{ secrets.SECRET }}
      
      - name: Fetch joke
        run: |
          JOKE_DATA=$(curl -s ${{ secrets.JOKE_URL }})
          SETUP=$(echo $JOKE_DATA | jq -r '.setup')
          PUNCHLINE=$(echo $JOKE_DATA | jq -r '.punchline')
          echo "<details>" > joke.txt
          echo "  <summary style=\"cursor: pointer; color: #0366d6;\">$SETUP</summary>" >> joke.txt
          echo "  <p style=\"margin-left: 20px;\">$PUNCHLINE</p>" >> joke.txt
          echo "</details>" >> joke.txt

      - name: Fetch latest blog posts
        run: |
          BLOG_DATA=$(curl -s https://atakangul.com/blogs/most-viewed)
          echo "Raw API response:"
          echo "$BLOG_DATA"
          if jq -e . >/dev/null 2>&1 <<<"$BLOG_DATA"; then
            echo $BLOG_DATA | jq -r 'if type == "array" then .[0:3] else . end | if type == "array" then map("<li>\n  <strong>" + (.title // "No Title") + "</strong>\n  <p>Topic: " + (.description // "No Description") + "</p>\n  <p><a href=\"https://atakangul.com/blogs/" + (.url // "") + "\">Read Article</a></p>\n</li>") | join("\n") else "Error: Unexpected data structure" end' > blog_posts.txt
          else
            echo "Error: Invalid JSON response from API" > blog_posts.txt
          fi
          echo "Processed blog posts:"
          cat blog_posts.txt

      - name: Update README
        run: |
          awk '
          BEGIN {
            joke = 0
            blog = 0
          }
          /<h2>You like jokes?<\/h2>/ {
            print
            print "<details>"
            system("cat joke.txt")
            joke = 1
            next
          }
          joke && /<\/details>/ {
            joke = 0
            next
          }
          /<h2>I Like Writing Blog \(Updated every 10 minutes\)<\/h2>/ {
            print
            print "<ul>"
            system("cat blog_posts.txt")
            print "</ul>"
            blog = 1
            next
          }
          blog && /<\/ul>/ {
            blog = 0
            next
          }
          !joke && !blog {
            print
          }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.USERNAME }}"
          git add README.md
          git commit -m "Update README with latest joke and blog posts" || exit 0
          git push https://${{ secrets.SECRET }}@github.com/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}.git
