name: Daily Joke Update

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          repository: AtakanG7/AtakanG7

      - name: Fetch joke and update README
        run: |
      
          JOKE_DATA=$(curl -s 'https://official-joke-api.appspot.com/random_joke')
          SETUP=$(echo $JOKE_DATA | jq -r '.setup')
          PUNCHLINE=$(echo $JOKE_DATA | jq -r '.punchline')
          
          JOKE="## **10 min/joke:**\n\n$SETUP\n\n$PUNCHLINE"
         
          sed -i '/<!-- JOKE-START -->/,/<!-- JOKE-END -->/c\<!-- JOKE-START -->\n'"- $JOKE"'\n<!-- JOKE-END -->' README.md
          
          if ! grep -q "<!-- JOKE-START -->" README.md; then
            echo -e "\n<!-- JOKE-START -->\n- $JOKE\n<!-- JOKE-END -->" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update daily joke" || exit 0
          git push
